extensions:
    wissend-setting-index:
        module: pim/common/simple-view
        #aclResourceId: wissend_settings
        config:
            template: pim/template/common/default-template

    wissend-setting-index-grid-container:
        module: pim/common/simple-view
        parent: wissend-setting-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    wissend-setting-index-user-navigation:
        module: pim/menu/user-navigation
        parent: wissend-setting-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

            
    wissend-setting-index-grid-title:
        module: pim/common/grid-title
        parent: wissend-setting-index
        targetZone: title
        config:
            countable: false
            title: pim_menu.item.wissend_setting

    wissend-setting-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: wissend-setting-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-wissend-settings
   